### ISSUE TITLE
Is this repo obsolete?

### ISSUE THREAD

**Issue by rolfedh** [golemfactory/golem_website#2]
@banasiakadam60 It looks like the content on the website has moved beyond the content in https://github.com/golemfactory/golem_website/blob/master/index.html.
For example, index.html on the website contains "APPLICATION REGISTRY & TRANSACTION FRAMEWORK" but the same file here does not.

**Comment by badb** [comment]
Yes, this repository contains old version of Golem website. The new version is not kept in public repo. I've added information about this in repository description.

**Comment by rolfedh** [comment]
@badb You should delete this repo.
